      - name: Download & unpack ZIP (strict)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ZIP_URL: ${{ github.event.inputs.url }}
        run: |
          set -euo pipefail
          sudo apt-get update -y >/dev/null
          sudo apt-get install -y unzip >/dev/null

          echo "→ download: $ZIP_URL"
          
          HTTP_CODE=$(curl -sSL -w '%{http_code}' \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/octet-stream" \
            -o sync.zip "$ZIP_URL")
          if [ "$HTTP_CODE" != "200" ]; then
            echo "Download failed HTTP $HTTP_CODE"
            exit 1
          fi

          file sync.zip || true
          if ! unzip -tq sync.zip >/dev/null 2>&1; then
            echo "Archive is not a valid ZIP (unzip -t failed)"
            head -c 200 sync.zip || true
            exit 1
          fi

          rm -rf unpack
          mkdir -p unpack
          unzip -q -o sync.zip -d unpack

          shopt -s dotglob nullglob
          if [ -d unpack/* ] && [ "$(ls -1 unpack | wc -l)" = "1" ]; then
            mv unpack/* unpack_root && rm -rf unpack && mv unpack_root unpack
          fi

          if [ ! -d unpack ] || [ -z "$(ls -A unpack)" ]; then
            echo "Nothing unpacked (unpack/ is empty or missing)"
            exit 1
          fi

      - name: Copy new contents
        run: |
          set -euo pipefail

          [ -d unpack ]
          rsync -a --delete unpack/ .
